config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "admin/dashboard#index"
  devise_scope :user do
    get "/users/sign_up", :to => "admin/dashboard#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    resources :articles, only: [:index, :show]
    resources :photos, only: [:index, :show]
  end

  match '*path', to: redirect('/'), via: :get

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos
  # attr_accessor :title, :body, :photos
  def self.recent(number)
    Article.last(number).reverse
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :article
  mount_uploader :image, ImageUploader
  def self.recent(number)
    Photo.last(number).reverse
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  def index
    ordered_articles = Article.all.order(created_at: :desc)
    articles = ordered_articles.select{ |a| a.published == true}
    render status: 200, json: articles
  end

  def show
    article = Article.find(params[:id])

    render status: 200, json: article
  end

end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController
  def index
    photos = Photo.all
    render status: 200, json: photos
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  after_action :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

#
# def index
#   @articles = Article.all
# end
# # Lorenzo first guess for show
# def show
#   @article = Article.find(params[:id])
#   @photos = @article.photos
# end
#
#
# def new
#   @article = Article.new
# end
#
# def create
#   @article =  Article.create(article_params)
#   if @article.save
#     images_params.each do |image|
#       @article.photos.create(image: image)
#     end
#     redirect_to article_path(@article), notice: "Hey a new article"
#   else
#     render :new
#   end
# end
#
# def edit
#   @article = Article.find(params[:id])
# end
#
# def update
#   @article = Article.find(params[:id])
#   @article.update(article_params)
#
#   if @article.save
#     images_params.each do |image|
#       @article.photos.create(image: image)
#     end
#     redirect_to article_path(@article), notice: "Hey article updated"
#   else
#     render :edit
#   end
# end
#
# def destroy
#   @article = Article.destroy(params[:id])
#   redirect_to articles_path
# end
#
#
# private
# def article_params
#   params.require(:article).permit(:id, :title, :body, :photos)
# end
#
# def images_params
#   params[:images].present? ? params.require(:images) : []
# end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper

  def generate_url(url, params = {})
    uri = URI(url)
    uri.query = params.to_query
    uri.to_s
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/articles/_form.html.erb
<% if @article.new_record? %>
  <%= render partial: "form_new", resource: @article %>
<% else %>
  <%= render partial: "form_edit", resource: @article %>
<% end %>

app/views/admin/articles/_form_edit.html.erb
<%= semantic_form_for [:admin, @article], builder: Formtastic::FormBuilder do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :lat %>
    <%= f.input :lng %>
    <%= f.input :body, as: :ckeditor %>
    <%= f.input :published %>
    <hr>
    <%= f.actions %>
  <% end %>
<% end %>

<% if @article.photos %>
  <% @article.photos.each do |photo| %>
    <%= semantic_form_for [:admin, @article,photo], builder: Formtastic::FormBuilder do |t| %>
    <%= t.semantic_errors %>
      <%= t.inputs do %>
        <%= t.input :description %>
        <%= t.input :featured %>
        <div class='form_additional_field'>
          <%= image_tag photo.image.thumbnail %>
          <%= link_to "Delete", admin_article_photo_path(@article,photo.id ), method: :delete %>
        </div>
        <%= t.actions %>
      <% end %>
    <% end %>
  <% end %>
<% end %>



<%= semantic_form_for [:admin, @article,@article.photos.new], builder: Formtastic::FormBuilder do |k| %>
  <%= k.semantic_errors %>
  <%= k.inputs do %>
    <%= k.input :description %>
    <%= k.input :featured %>
    <%= k.input :image %>
    <%= k.actions %>
  <% end %>
<% end %>

app/views/admin/articles/_form_new.html.erb
<%= semantic_form_for [:admin, @article],html: {:multipart => true} ,builder: Formtastic::FormBuilder do |f| %>
  <%= f.semantic_errors %>

  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :lat, input_html: {value: "#{@latitude}"}  %>
    <%= f.input :lng, input_html: {value: "#{@longitude}"}  %>
    <%= f.input :body, as: :ckeditor %>
    <%= f.input :published %>
    <% end %>
  <%= f.actions %>
<% end %>

app/views/admin/dashboard/_map.html.erb
<div>
  <div id="map" style='width: 100%; height: 600px;'>
    <script type="text/javascript">
      width='100%';	// the width of the embedded map in pixels or percentage
      height='600';	// the height of the embedded map in pixels or percentage
      border='1';	// the width of the border around the map (zero means no border)
      shownames='true';	// to display ship names on the map (true or false)
      latitude='50.543472';	// the latitude of the center of the map, in decimal degrees
      longitude='2.654068';	// the longitude of the center of the map, in decimal degrees zoom='9';	// the zoom level of the map (values between 2 and 17)
      maptype='0';	// use 0 for Normal Map, 1 for Satellite, 2 for OpenStreetMap
      trackvessel='244670249';	// MMSI of a vessel (note: vessel will be displayed only if within range of the system) - overrides "zoom" option
      fleet='vanmarle.n@gmail.com';	// the registered email address of a user-defined fleet (user's default fleet is used)
    </script>

    <script type="text/javascript" src="//www.marinetraffic.com/js/embed.js"></script>
  </div>
</div>

app/views/articles/edit.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
<div class="form-group">
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, placeholder: "Name" %>
    <br/>
  </div>
  <div class="form-group">

    <label>Body</label>
    <%= f.text_field :body, as: :html_editor %>
    <br />
  </div>

  <div class="form-group">
    <label>Image Upload</label>
    <%= file_field_tag "images[]", type: :file, multiple: true %>
    <br />
  </div>

  <div class="actions">
  <%= f.submit "Create", class: "btn btn-primary"%>
  </div>

</div>
<% end %>

app/views/articles/index.html.erb
<style>
.jumbotron {
  background-image: url("http://res.cloudinary.com/lorenzocloudinary/image/upload/v1502718958/stormalong/IMG_0271.jpg");
  background-repeat: no-repeat;
  background-position: center;
  height: 100%;
  color: white;
  text-shadow: black 0.3em 0.3em 0.3em;
}
</style>

<div class="jumbotron">
  <h1 >Cool website</h1>
</div>

<hr/>

<script type="text/javascript">
width='100%';	// the width of the embedded map in pixels or percentage
height='500';	// the height of the embedded map in pixels or percentage
border='1';	// the width of the border around the map (zero means no border)
shownames='false';	// to display ship names on the map (true or false)
latitude='37.4460';	// the latitude of the center of the map, in decimal degrees
longitude='24.9467';	// the longitude of the center of the map, in decimal degrees zoom='9';	// the zoom level of the map (values between 2 and 17)
maptype='1';	// use 0 for Normal Map, 1 for Satellite, 2 for OpenStreetMap
trackvessel='244670249';	// MMSI of a vessel (note: vessel will be displayed only if within range of the system) - overrides "zoom" option
fleet='vanmarle.n@gmail.com';	// the registered email address of a user-defined fleet (user's default fleet is used)
</script> <script type="text/javascript" src="//www.marinetraffic.com/js/embed.js"></script>

<% if user_signed_in? %>
  <%= link_to "add an article", new_article_path, class: "btn btn-primary"  %>
<% end %>

<div class="row">
  <% @articles.each do |article|%>
    <div class="col-sm-6 text-center">
      <div class="form-group">
        <h3><b><%= link_to article.title, article_path(article.id) %></b></h3>
      </div>
      <div class="form-group">
        <p><%= article.body %></p>
      </div>
      <div class="form-group">
        <% article.photos.each do |photo| %>
        <%= image_tag photo.image %>
        <% end %>
      </div>
    </div>
  <%end%>
</div>
<hr />

<%= render 'shared/footer' %>

app/views/articles/new.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
<div class="form-group">
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, placeholder: "Name" %>
    <br/>
  </div>
  <div class="form-group">

    <label>Body</label>
    <%= f.text_field :body, placeholder: "Blog body" %>
    <br />
  </div>

  <div class="form-group">
    <label>Image Upload</label>
    <%= file_field_tag "images[]", type: :file, multiple: true %>
    <br />
  </div>

  <div class="actions">
  <%= f.submit "Create", class: "btn btn-primary" %>
  </div>

</div>
<% end %>

app/views/articles/show.html.erb
<%= @article.title %>
<%= @article.body %>
<% @photos.each do |photo| %>
  <%= image_tag photo.image %>
<% end %>

<% if user_signed_in? %>
  <%= link_to "edit this article", edit_article_path(@article), class: "btn btn-primary" %>
  <%= link_to "Delete this article", article_path(@article), method: :delete, class: "btn btn-primary",
  data: { confirm: "Are you sure to delete this lovely article?"} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <title>Stormalong</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <% if !user_signed_in? %>
      <%= link_to raw("<span class='glyphicon glyphicon-off' aria-hidden='true'></span>"), new_user_session_path %>
    <% else %>
     <%= link_to raw("<span class='glyphicon glyphicon-off' aria-hidden='true'></span>"), destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</footer>